spring.application.name=justice-gov-service
server.port=1576

# The "Bridge" to your GitHub settings
spring.config.import=optional:configserver:http://localhost:8888

# The "Bridge" to Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
